export const LOAD_CHART_DATA_SUCCESS = 'LOAD_CHART_DATA_SUCCESS';

export const AJAX_CALL_BEGIN = 'AJAX_CALL_BEGIN';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
